### ISSUE TITLE
Won't install with 4.4.x

### ISSUE THREAD

**Issue by jblaine** [bestpractical/rt-extension-spawnlinkedticketinqueue#3]
Any chance of this being updated?
```
**** Error: Your installed version of RT (4.4.2-21-gd8c6547) is too new; this extension
            only works with versions older than 4.4.0. 
```

**Comment by sartak** [comment]
The functionality is included in RT 4.4.0, so the extension is no longer needed. Please see the UPGRADING-4.4 doc that ships with RT.

Best,
Shawn 

iPhoneから送信

H29/09/06 21:18、Jeff Blaine <notifications@github.com> のメッセージ:
